import Card from 'components/card'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 grid place-items-center">
        <h1 className="text-6xl text-center font-bold">
          Welcome to{' '}
          <a
            href="https://nextjs.org"
            className="text-blue-600 hover:underline focus:underline active:underline"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 text-2xl">
          Get started by editing{' '}
          <code className="bg-gray-100 rounded p-3 text-xl">
            pages/index.tsx
          </code>
        </p>

        <div className="grid md:grid-cols-2">
          <Card href="https://nextjs.org/docs" title="Documentation">
            Find in-depth information about Next.js features and API.
          </Card>

          <Card href="https://nextjs.org/learn" title="Learn">
            Learn about Next.js in an interactive course with quizzes!
          </Card>

          <Card
            href="https://github.com/vercel/next.js/tree/master/examples"
            title="Examples"
          >
            Discover and deploy boilerplate example Next.js projects.
          </Card>

          <Card href="https://vercel.com/new" title="Deploy">
            Instantly deploy your Next.js site to a public URL with Vercel.
          </Card>
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t justify-center items-center">
        <a
          href="https://vercel.com"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow"
        >
          Powered by{' '}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
